# 端口号
server:
  port: 9999
spring:
  profiles:
    # 运行环境 dev|test|prod,根据active动态加载application-active.yml配置文件
    active: prod
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzuli?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zzuli
    password: zzuli
  # 发送邮件配置
  mail:
    port: 465
    host: smtp.qq.com
    username: 1807366859@qq.com
    password: bhminismyqwwebgf
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
        debug: true
# 日志配置文件的位置
logging:
  config: classpath:logback-spring.xml
  #部署的时候的配置
#    config: ./config/logback-spring.xml

# 自定义数据
data:
  # 线程池配置
  pool:
    corePoolSize: 10
    maximumPoolSize: 10
    keepAliveTime: 60
    capacity: 1

  # httpclient 配置
  # 单位为秒
  client:
    socketTimeout: 60
    connectTimeout: 60
    connectionRequestTimeout: 60
    retryCount: 3


  # FieldInfos
  field:
    fields:
#          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ017",fieldName: "羽毛球05-1",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ018",fieldName: "羽毛球05-2",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ019",fieldName: "羽毛球05-3",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ020",fieldName: "羽毛球05-4",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#
          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ021",fieldName: "羽毛球06-1",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ022",fieldName: "羽毛球06-2",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ023",fieldName: "羽毛球06-3",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ024",fieldName: "羽毛球06-4",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }

          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ025",fieldName: "羽毛球07-1",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ026",fieldName: "羽毛球07-2",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ027",fieldName: "羽毛球07-3",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
          - { beginTime: "19:30",endTime: "20:30",fieldNo: "YMQ028",fieldName: "羽毛球07-4",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ017",fieldName: "羽毛球05-1",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ018",fieldName: "羽毛球05-2",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ019",fieldName: "羽毛球05-3",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ020",fieldName: "羽毛球05-4",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }

#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ021",fieldName: "羽毛球06-1",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ022",fieldName: "羽毛球06-2",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ023",fieldName: "羽毛球06-3",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ024",fieldName: "羽毛球06-4",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ025",fieldName: "羽毛球07-1",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ026",fieldName: "羽毛球07-2",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ027",fieldName: "羽毛球07-3",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }
#          - { beginTime: "20:30",endTime: "21:30",fieldNo: "YMQ028",fieldName: "羽毛球07-4",fieldTypeNo: "03",price: "0.00",timeStatus: 1,fieldState: 0 }

  # 启动时间
  run:
    cron: 0 0 7 * * ?
  order:
    # 预约死锁间隔时间
    intervalTime: 500
    # 预约重试次数
    retryCount: 5


