# 端口号
server:
  port: 6666
spring:
  profiles:
    # 运行环境 dev|test|prod,根据active动态加载application-active.yml配置文件
    active: prod
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzuli?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zzuli
    password: zzuli
  # 发送邮件配置
  mail:
    port: 465
    host: smtp.qq.com
    username: 1807366859@qq.com
    password: bhminismyqwwebgf
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
        debug: true
# 查询时 java 驼峰命名自动转为_线形式
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
# 日志配置文件的位置
logging:
  config: classpath:logback-spring.xml
  # 部署的时候的配置
  # config: ./config/logback-spring.xml

data:
  # jwt配置
  jwt:
    header: "Authorization" # token返回头部
    tokenPrefix: "Bearer " # token前缀
    secret: "sdsdf564541fzjgasdgf165" # 密钥
    expireTime: 30 # token有效时间 (分钟)

  # 线程池配置
  pool:
    corePoolSize: 10
    maximumPoolSize: 10
    keepAliveTime: 60
    capacity: 1

  # httpclient 配置
  # 单位为秒
  client:
    socketTimeout: 60
    connectTimeout: 60
    connectionRequestTimeout: 60
    retryCount: 3

  # 打卡数据配置
  common:
    # 最近一次核算日期
    lastTime: "2022-08-01"

  # 启动时间
  run:
    cron: 0 21 8 * * ?





